### ISSUE TITLE
Self-registering modules

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/wlanpi-fpms#1]
Move some of the internal features (e.g. modes) to dedicated, external self-registering packages. 

Candidates for this work include AP mode, Server mode and wireless console.

If the modules are present, they will present a well defined data structure (maybe in JSON format) that can be used to integrate in to the FPMS menu system automatically.

**Comment by wifinigel** [comment]
Some initial thoughts on the registration process:
1. Provide several folders which correspond to different leaves off the static menu system
2. As a modules is installed on the wlanpi, it puts its menu registration YAML file in the appropriate leaf location
3. Can support both shell & python module calls

Sample YAML files that would be parsed & grafted on to the menu system:

```
# a new menu item
name: Shutdown
action:
    call_type: shell
    call_location: /usr/bin
    call: 'shutdown -now'
```
```
# multiple options off new menu item
name: 'List services'
action:
    - {name: 'Show FPMS details', action: {call_type: shell, call_location: /usr/bin, call: 'ps -a | grep fpms'}}
    - {name: 'Show netinfo details', action: {call_type: shell, call_location: /usr/bin, call: 'ps -a | grep netinfo'}}
```
```
# a python call menu item (module is read in and provided function executed)
name: 'Do something python'
action:
    call_type: python
    call_location: /opt/wlanpi/util_folder/module.py
    call: do_something()
```
